### ISSUE TITLE
HTML not rendered correctly

### ISSUE THREAD

**Issue by tomasbjerre** [jenkinsci/violations-plugin#70]
Need to look into this...

![jenkins_violations_plugin](https://cloud.githubusercontent.com/assets/439571/8346510/f88765fc-1afd-11e5-867d-c0250ced37e4.PNG)

**Comment by kheremos** [comment]
Could it be from this commit:
https://github.com/jenkinsci/violations-plugin/commit/6dcbef2114adb0f9c01a0a927105fcf80a414e4d

It looks like the second table below is getting escaped when it shouldn't be.  Specifically the less than and ampersands.  Around line 69 of the index.jelly, it calls the violations summary, this is the content that is getting escaped either twice or unnecessarily.   

I hunted this down by searching for \<h3> tags. The opening tag occurs twice for this page, once correctly, and once escaped.

@kohsuke Did you experience this at all in your testing of your contribution?  If it's due to something on my end, I'd be happy to fix it!

**Comment by tomasbjerre** [comment]
There is HTML in:
violations-plugin/src/main/java/hudson/plugins/violations/render/FileModelProxy.java
That should be moved to:
/violations-plugin/src/main/resources/hudson/plugins/violations/render/FileModelProxy/index.jelly
There are a bunch of bugs here... like hard coded references to images instead of using rooUrl-variable (https://wiki.jenkins-ci.org/display/JENKINS/Basic+guide+to+Jelly+usage+in+Jenkins#BasicguidetoJellyusageinJenkins-PredefinedURLs)

**Comment by tomasbjerre** [comment]
Included in alpha-2: https://github.com/jenkinsci/violations-plugin/releases/tag/violations-0.8.0-alpha-2

**Comment by kheremos** [comment]
Looks much better, although I can't really see the difference between the
two tables:
[image: Inline image 1]
Just wanted to send you a quick message to let you know I updated to
Alpha-2.  And that all appears well from my end.  Also, is there a way to
disable the Visual Studio links?  None of my projects are related to Visual
Studio, and I don't think they ever will be, as we're trying to go as
open-source as possible...
